config/routes.rb
Rails.application.routes.draw do
  resources :calls do
    member do
      get :download
    end
  end

  resources :services

  resources :corp_packs do
    resources :services, only: :index, controller: 'corp_packs/services'
  end

  resources :corp_pack_services

  resources :players do

    collection do
      get :by_phone
    end

  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/admin_lte', to: 'admin_lte#index'
  get '/admin_lte/v2', to: 'admin_lte#index2'



  get '/admin_lte/top-nav', to: 'admin_lte#top_nav'
  get '/admin_lte/boxed', to: 'admin_lte#boxed'
  get '/admin_lte/fixed', to: 'admin_lte#fixed'
  get '/admin_lte/collapsed-sidebar', to: 'admin_lte#collapsed_sidebar'


  get '/admin_lte/widgets', to: 'admin_lte#widgets'


  get '/admin_lte/charts/chart_js', to: 'admin_lte#chart_js'
  get '/admin_lte/charts/morris', to: 'admin_lte#morris'
  get '/admin_lte/charts/flot', to: 'admin_lte#flot'
  get '/admin_lte/charts/inline', to: 'admin_lte#inline'


  get '/admin_lte/tables/simple', to: 'admin_lte#simple'
  get '/admin_lte/tables/data', to: 'admin_lte#data'
  get '/admin_lte/tables/data2', to: 'admin_lte#data2'

  get '/admin_lte/forms/general', to: 'admin_lte#general_forms'
  get '/admin_lte/forms/advanced', to: 'admin_lte#advanced_forms'


  namespace :online_pbx do
    post '/', to: 'events#create'
  end

  root to: 'home#index'
end

app/models/corp_pack.rb
class CorpPack < ApplicationRecord
  attr_accessor :date_from, :date_to

  belongs_to :manager, class_name: 'User'
  belongs_to :call, optional: true

  has_many :corp_pack_services
  has_many :services, through: :corp_pack_services

  belongs_to :player

  accepts_nested_attributes_for :corp_pack_services

  validates :manager, presence: true

  validates :date, presence: true, format: /\A\d{2}\.\d{2}\.\d{4}\Z/
  validates :time, presence: true

  validates :prepayment_sum, numericality: true, allow_blank: true

  validate :validate_datetime

  before_save :assign_datetime

  ATTR_VALUES = {
    mode: [
      'Выездной квест',
      'Аренда зала № 1',
      'Аренда зала № 2',
      'Аренда зала № 3',
      'Аренда зала № 4',
      'Аренда зала № 5',
      'Аренда зала № 6',
      'День рождения (ИЦ закрыт)',
      'Детский день рождения',
      'Взрослый день рождения',
      'Корпоратив',
      'Кафе взрослый',
      'Кафе детский',
      'Корпоратив закрытие'
    ],

    status: [
      'Входящий запрос',
      'Забронировано',
      'Бронь подтверждена',
      'Внесена предоплата',
      'Бронь отменена',
      'Завершен',
      'Отложено'
    ],

    payment_type: [
      'Наличные',
      'Карта',
      'Смешанный',
      'Рассчетный счет'
    ],

    game_center: [
      'Сургут'
    ],

    prepayment_type: :payment_type,
    info_source: [ 'Сайт', 'Звонок', 'Визит', 'Другое' ]
  }


  def profit
    0
  end

  def self.new_parse_dates(params)
    new.assign_params(params)
  end

  def assign_params(params)
    date = params.delete(:date)
    time = params.delete(:time)

    self.attributes = params

    if date && date !~ /\A\d{2}\.\d{2}\.\d{4}\Z/
      @date_invalid = true
    else
      self.date = Date.strptime(date, Date::DATE_FORMATS[:default])
    end

    if time && time !~ /\d{2}:\d{2}/
      @time_invalid = true
    else
      self.time = time
    end

    self
  end

  def validate_datetime
    errors.add(:date, :invalid) if @date_invalid
    errors.add(:time, :invalid) if @time_invalid
  end

  def time
    if t = self[:time]
      "#{t.hour}:#{t.min.to_s.rjust(2, '0')}"
    end
  end

  def date_and_time
    "#{date} #{time}"
  end

  def assign_datetime
    self.datetime = self.date.to_time + self[:time].hour.hours + self[:time].min.minutes    
  end
end

app/controllers/corp_packs/services_controller.rb
class CorpPacks::ServicesController < ApplicationController
  def index
    @corp_pack = CorpPack.find(params[:corp_pack_id])
    @services = Service.select("services.*, corp_pack_services.id as cps_present").joins("left outer join corp_pack_services on corp_pack_services.service_id = services.id and corp_pack_services.corp_pack_id = #{@corp_pack.id}")
    render template: 'services/index', layout: 'blank'

  end
end

app/controllers/corp_packs_controller.rb
class CorpPacksController < ApplicationController
  def index
    params[:sort_by]    ||= 'created_at'
    params[:sort_order] ||= 'desc'

    logger.info "SEARCH: #{search_attrs}"
    logger.info "QUERY: #{query_attrs}"

    @corp_packs = CorpPack.where(query_attrs).order("\"#{params[:sort_by]}\" #{params[:sort_order]}").paginate(page: params[:page], per_page: PER_PAGE)
    @corp_pack = CorpPack.new(search_attrs)

    logger.info "CORP PACK is #{@corp_pack.attributes}"

    if request.xhr?
      render partial: 'table'
    end
  end

  def new
    @corp_pack = CorpPack.new
  end

  def edit
    @corp_pack = CorpPack.find(params[:id])

    render action: :new
  end

  def create
    logger.info "PARAMS: #{corp_pack_params}"
    @corp_pack = CorpPack.new_parse_dates(corp_pack_params)


    if @corp_pack.save
      redirect_to corp_packs_path, notice: "Корп. пакет добавлен"
    else
      save_error
      logger.info @corp_pack.errors.messages
      render template: 'corp_packs/new'
    end
  end

  def update
    @corp_pack = CorpPack.find(params[:id])
    @corp_pack.assign_params(corp_pack_params)

    if @corp_pack.save
      redirect_to corp_packs_path, notice: "Корп. пакет сохранен"
    else
      save_error
      logger.info @corp_pack.errors.messages
      render template: 'corp_packs/new'
    end
  end

  def destroy
    @corp_pack = CorpPack.find(params[:id])
    @corp_pack.delete

    redirect_to corp_packs_path
  end

  def corp_pack_params
    _params = params.require(:corp_pack).permit(
      :manager_id, :game_center,
      :mode, :status,
      :call_id,

      :prepayment_type, :prepayment_sum, :prepayment_deadline,

      :payment_type,

      :date, :time,

      :player_id,
      corp_pack_services_attributes: [ :confirmed, :ordered, :price, :cost, :remind_at, :comment, :service_id, :id ]
    )

    # format_date_ru(_params, :date)

    _params
  end

  protected

  def search_attrs
    attrs = {}

    params[:corp_pack].try(:each) do |param, value|
      # next if %w(date_from date_to).include?(param)
      attrs[param] = value if value.present? && value != [""]
    end

    attrs
  end

  def query_attrs
    result = search_attrs.reject { |name, value| %w(date_from date_to).include?(name) }
    f, t = search_attrs['date_from'], search_attrs['date_to']

    if f || t
      from = f && Date.parse(f).to_time || 10.years.ago
      to   = t && (Date.parse(t).to_time + 1) || 10.years.from_now

      result[:datetime] = (from .. to)
    end

    result
  end

end

app/helpers/corp_packs/services_helper.rb
module CorpPacks::ServicesHelper
end

app/helpers/corp_packs_helper.rb
module CorpPacksHelper
end

app/views/corp_packs/_control_icons.slim
a href=edit_corp_pack_path(corp_pack)
  .i.fa.fa-pencil.fa-hover
br
= link_to corp_pack_path(corp_pack, authenticity_token: form_authenticity_token), method: :delete, data: {confirm: "Вы уверены?"} do
  .i.fa.fa-trash.fa-hover

app/views/corp_packs/_form.slim
= form_for(corp_pack) do |f|
  .box-body
    .row
      .col-md-4
        = render "shared/form_group", form: f, record: corp_pack, attribute: :manager_id, input_type: :select, select_options: User.all.map {|user| [user.name, user.id]}
      .col-md-4
        = render "shared/form_group", form: f, record: corp_pack, attribute: :game_center, input_type: :select, select_options: CorpPack::ATTR_VALUES[:game_center]

    .row
      .col-md-4
        = render "shared/form_group", form: f, record: corp_pack, attribute: :mode, input_type: :select, select_options: CorpPack::ATTR_VALUES[:mode]

      .col-md-4
        = render "shared/form_group", form: f, record: corp_pack, attribute: :status, input_type: :select, select_options: CorpPack::ATTR_VALUES[:status]

    .row
      .col-md-4
        = render "shared/form_group", form: f, record: corp_pack, attribute: :call_id, input_type: :select, select_options: [["-- не присвоен --", nil]] + Call.recent.inbound.map { |call| [ "#{call.time_tag} #{call.caller}", call.id ] }



  .box-header.with-border
    h3.box-title  Предоплата


  .box-body
    .row
      .col-md-4
        = render "shared/form_group", form: f, record: corp_pack, attribute: :prepayment_type, input_type: :select, select_options: CorpPack::ATTR_VALUES[:payment_type]

      .col-md-4
        = render "shared/form_group", form: f, record: corp_pack, attribute: :prepayment_sum

      .col-md-4
        = render "shared/date_input", form: f, record: corp_pack, attribute: :prepayment_deadline

  .box-header.with-border
    h3.box-title  Итоговая оплата


  .box-body
    .row
      .col-md-4
        = render "shared/form_group", form: f, record: corp_pack, attribute: :payment_type, input_type: :select, select_options: CorpPack::ATTR_VALUES[:payment_type]


  .box-header.with-border
    h3.box-title  Дата и время проведения


  .box-body
    .row
      .col-md-4
        = render "shared/date_input", form: f, record: corp_pack, attribute: :date

      .col-md-4
        = render "shared/time_input", form: f, record: corp_pack, attribute: :time

  .box-header.with-border
    h3.box-title  Информация об игроке

  .box-body
    .row
      .col-md-4
        - coll = corp_pack.player && [corp_pack.player] || []
        = render "shared/select_input", form: f, record: corp_pack, attribute: :player_id, collection: coll, no_blank: true, error_attribute: :player

      .col-md-3
        label &nbsp;
        button.btn.btn-block.btn-primary id="create-player-btn" data-url=new_player_path(popup: '1') Создать и добавить игрока

    .row
      .col-md-4
        label Проверка наличия игрока по телефону

        .form-group
          .input-group
            .input-group-addon
              i.fa.fa-phone

            / = f.text_field attribute, class: "form-control", 'data-inputmask': '"mask": "+7 (999) 999-9999"', 'data-mask': true

            input id="player-phone" type="text" class='form-control' data-inputmask='"mask": "+7 (999) 999-9999"' data-mask=true

      .col-md-1
        label &nbsp;
        button.btn.btn-block.btn-primary#find-player-by-phone Найти



  .box-header.with-border
    h3.box-title  Доп. Услуги

  .box-body
    a name="services"
    table.table.table-bordered.table-hover
      thead
        tr
          th #
          th Подтверждена
          th Услуги
          th Комментарий
          th Дата напоминания
          th Заказана
          th Цена для клиента
          th Себестоимость
          th
      tbody
        - @corp_pack.corp_pack_services.each do |cps|
          = f.fields_for :corp_pack_services, cps do |fields|
            = render 'service', fields: fields, cps: cps

        - cps = @corp_pack.corp_pack_services.new
        = f.fields_for :corp_pack_services, cps do |fields|
          = render 'service', fields: fields, cps: cps, hidden: true


    .row
      .col-md-2
        - url = @corp_pack.new_record? ? services_path : corp_pack_services_path(@corp_pack)
        button.btn.btn-block.btn-primary#add_service_btn data-url=url Добавить услугу

  .box-footer
    = f.submit(corp_pack.new_record? ? "Создать" : "Сохранить")

app/views/corp_packs/_search.slim
- @model = :corp_pack

= form_for @corp_pack, url: corp_packs_path, method: :get do |form|
  .box-body
    .row
      .col-md-4
        = render "shared/simple_date_input", form: form, attribute: :date_from, label: "Дата от"

      .col-md-4
        = render "shared/simple_date_input", form: form, attribute: :date_to, label: "Дата по"

      .col-md-4
        = render "shared/simple_date_input", form: form, attribute: :prepayment_deadline

    .row
      .col-md-4
        = render "shared/simple_select_input", form: form, attribute: :info_source, select_options: Player::ATTR_VALUES[:info_source]

      .col-md-4
        = render "shared/simple_select_input", form: form, attribute: :status, select_options: CorpPack::ATTR_VALUES[:status], input_attributes: { multiple: true }

      .col-md-4
        = render "shared/simple_select_input", form: form, attribute: :mode, select_options: CorpPack::ATTR_VALUES[:mode], input_attributes: { multiple: true }

    .row
      .col-md-4
        = render "shared/collection_select", form: form, attribute: :manager_id, collection: User.all

      .col-md-4
        = render "shared/collection_select", form: form, attribute: :player_id, collection: Player.all

      .col-md-4
        = render "shared/simple_date_input", form: form, attribute: :created_at, label: "Создано"

    .row
      .col-md-4
        = render "shared/simple_select_input", form: form, attribute: :game_center, select_options: CorpPack::ATTR_VALUES[:game_center], no_blank: true

      .col-md-4
        = render "shared/simple_date_input", form: form, attribute: :prepayed_at


  .box-footer
    .row
      .col-md-12
        / div style='float:right'
        = form.submit("Найти")

app/views/corp_packs/_service.slim
- hidden ||= false

tr.service-row data-cps-id=cps.id id=('new-service-row' if hidden)
  
  td.service-num = cps.corp_pack.corp_pack_services.index(cps) + 1
  td= fields.check_box  :confirmed
  td.service-name = cps.service.try(:name)
  td= fields.text_field :comment
  td= fields.text_field :remind_at
  td= fields.check_box :ordered
  td= fields.text_field :price
  td
    = fields.text_field :cost
    = fields.hidden_field :service_id, class: 'service-id-input'
    - unless cps.new_record?
      = fields.hidden_field :id

  td
    - if cps.new_record?
      a.remove-service
        .i.fa.fa-trash.fa-hover
    - else           
      = link_to corp_pack_service_path(cps, authenticity_token: form_authenticity_token), method: :delete, data: {confirm: "Вы уверены?"} do
          .i.fa.fa-trash.fa-hover

app/views/corp_packs/_table.html.slim
= render 'shared/sortable_table', collection: @corp_packs, \
  columns: [:time, :player, :status, :comment, :prepayment_sum,
            :prepayment_deadline, :profit, :mode, :game_center, :created_at, nil ], \
  skip: [:player_id, :profit, :comment, :player ], \
  values: {:player => 'player.try(:name)', :time => :date_and_time, nil => '_control_icons' }

app/views/corp_packs/index.slim
h2.page-header Корп. пакеты
/.row
  .col-md-12
    h2 Корп. пакеты
.row
  .col-md-12
    .box.box-primary
      .box-header.with-border
        h3.box-title Параметры поиска
      = render 'search'

      / .box-header.with-border
        h3.box-title Корп. пакеты

      .box-body
        = render 'table'

      .box-footer
        = link_to "Создать", new_corp_pack_path

app/views/corp_packs/new.slim
.row
  .col-md-12
    .box.box-primary
      .box-header.with-border
        h3.box-title  Информация об игре
      = render "form", corp_pack: @corp_pack


- content_for(:styles) do
  |
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/admin_lte/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/admin_lte/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/admin_lte/bower_components/Ionicons/css/ionicons.min.css">
    <!-- daterange picker -->
    <link rel="stylesheet" href="/admin_lte/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="/admin_lte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="/admin_lte/plugins/iCheck/all.css">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="/admin_lte/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css">
    <!-- Bootstrap time Picker -->
    <link rel="stylesheet" href="/admin_lte/plugins/timepicker/bootstrap-timepicker.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/admin_lte/bower_components/select2/dist/css/select2.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/admin_lte/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/admin_lte/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

- content_for :scripts do
  |
    <!-- jQuery 3 -->
    <script src="/admin_lte/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="/admin_lte/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Select2 -->
    <script src="/admin_lte/bower_components/select2/dist/js/select2.full.min.js"></script>
    <!-- InputMask -->
    <script src="/admin_lte/plugins/input-mask/jquery.inputmask.js"></script>
    <script src="/admin_lte/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
    <script src="/admin_lte/plugins/input-mask/jquery.inputmask.extensions.js"></script>
    <!-- date-range-picker -->
    <script src="/admin_lte/bower_components/moment/min/moment.min.js"></script>
    <script src="/admin_lte/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- bootstrap datepicker -->
    <script src="/admin_lte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!-- bootstrap color picker -->
    <script src="/admin_lte/bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
    <!-- bootstrap time picker -->
    <script src="/admin_lte/plugins/timepicker/bootstrap-timepicker.min.js"></script>
    <!-- SlimScroll -->
    <script src="/admin_lte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- iCheck 1.0.1 -->
    <script src="/admin_lte/plugins/iCheck/icheck.min.js"></script>
    <!-- FastClick -->
    <script src="/admin_lte/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="/admin_lte/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/admin_lte/dist/js/demo.js"></script>
    <!-- Page script -->

    <script src="/javascripts/datepicker-ru.js"></script>

    <script>
      $(function () {
        //Initialize Select2 Elements
        $('.select2').select2()

        //Datemask dd/mm/yyyy
        $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
        //Datemask2 mm/dd/yyyy
        $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
        //Money Euro
        $('[data-mask]').inputmask()

        //Date range picker
        $('#reservation').daterangepicker()
        //Date range picker with time picker
        $('#reservationtime').daterangepicker({ timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A' })
        //Date range as a button
        $('#daterange-btn').daterangepicker(
          {
            ranges   : {
              'Today'       : [moment(), moment()],
              'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
              'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
              'Last 30 Days': [moment().subtract(29, 'days'), moment()],
              'This Month'  : [moment().startOf('month'), moment().endOf('month')],
              'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            startDate: moment().subtract(29, 'days'),
            endDate  : moment()
          },
          function (start, end) {
            $('#daterange-btn span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
          }
        )

        //Date picker
        $('.date-picker').datepicker({
          format: "dd.mm.yyyy"
        })

        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass   : 'iradio_minimal-blue'
        })
        //Red color scheme for iCheck
        $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
          checkboxClass: 'icheckbox_minimal-red',
          radioClass   : 'iradio_minimal-red'
        })
        //Flat red color scheme for iCheck
        $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
          checkboxClass: 'icheckbox_flat-green',
          radioClass   : 'iradio_flat-green'
        })

        //Colorpicker
        $('.my-colorpicker1').colorpicker()
        //color picker with addon
        $('.my-colorpicker2').colorpicker()

        //Timepicker
        $('.timepicker').timepicker({
          showInputs: false
        })
      })
    </script>