config/routes.rb
Rails.application.routes.draw do
  resources :calls do
    member do
      get :download
    end
  end

  resources :services

  resources :corp_packs do
    resources :services, only: :index, controller: 'corp_packs/services'
  end

  resources :corp_pack_services

  resources :players do

    collection do
      get :by_phone
    end

  end
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/admin_lte', to: 'admin_lte#index'
  get '/admin_lte/v2', to: 'admin_lte#index2'



  get '/admin_lte/top-nav', to: 'admin_lte#top_nav'
  get '/admin_lte/boxed', to: 'admin_lte#boxed'
  get '/admin_lte/fixed', to: 'admin_lte#fixed'
  get '/admin_lte/collapsed-sidebar', to: 'admin_lte#collapsed_sidebar'


  get '/admin_lte/widgets', to: 'admin_lte#widgets'


  get '/admin_lte/charts/chart_js', to: 'admin_lte#chart_js'
  get '/admin_lte/charts/morris', to: 'admin_lte#morris'
  get '/admin_lte/charts/flot', to: 'admin_lte#flot'
  get '/admin_lte/charts/inline', to: 'admin_lte#inline'


  get '/admin_lte/tables/simple', to: 'admin_lte#simple'
  get '/admin_lte/tables/data', to: 'admin_lte#data'
  get '/admin_lte/tables/data2', to: 'admin_lte#data2'

  get '/admin_lte/forms/general', to: 'admin_lte#general_forms'
  get '/admin_lte/forms/advanced', to: 'admin_lte#advanced_forms'


  namespace :online_pbx do
    post '/', to: 'events#create'
  end

  root to: 'home#index'
end

app/models/player.rb
class Player < ApplicationRecord
  PHONE_REGEXP = /\+7 \(\d{3}\) \d{3}-\d{4}/

  validates :phone, uniqueness: true, format: PHONE_REGEXP, presence: true
  validate :additional_phone

  validates :email, uniqueness: true, format: Devise.email_regexp
  validates :name, presence: true

  attr_accessor :phone_no_mask

  ATTR_VALUES = {
    info_source: [ 'Друзья', 'Интернет', 'Соц. сети', 'Другое' ]
  }

  def additional_phone
    if self.phone2.present?
      unless phone2 =~ PHONE_REGEXP
        errors.add(:phone2, :invalid)
      end
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  layout :choose_layout

  def index
    @player  = Player.new

    params[:sort_by]    ||= 'created_at'
    params[:sort_order] ||= 'desc'

    scope    = Player.order("\"#{params[:sort_by]}\" #{params[:sort_order]}").paginate(page: params[:page], per_page: PER_PAGE)
    @players = search_scope(scope)
    @player  = Player.new(search_attrs)

    if request.xhr?
      render partial: 'table'
    end
  end

  def new
    if Rails.env.development?
      @player = Player.new(name: "Joe", phone: "+7 (916) 328-8901", city: "Сургут", email: "joe@surgut.com", male: true)
    else
      @player = Player.new(male: true)
    end
  end

  def create
    @player = Player.new(player_params)

    if request.xhr?
      if @player.save
        render json: { status: 'saved', id: @player.id, name: @player.name }
      else
        # render(partial: 'players/form', locals: {player: @player})
        render(partial: 'players/form', locals: {player: @player})
      end

      return
    end

    respond_to do |format|
      format.html do
        if @player.save
          redirect_to players_path, notice: "Игрок добавлен"
        else
          save_error
          render template: 'players/new'
        end
      end
    end
  end

  def edit
    @player = Player.find(params[:id])
    render(action: :new)
  end

  def update
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to players_path, notice: "Игрок сохранен"
    else
      save_error
      render(action: :new)
    end
  end

  def player_params
    params.require(:player).permit(
      :name, :phone, :email, :phone2, :city, :blacklist,
      :receive_email, :receive_sms, :male, :child_name, :child_birth_date,
      :info_source, :comment
    )
  end

  def by_phone
    player = Player.find_by_phone(params[:phone])
    render json: {id: player.try(:id), name: player.try(:name)}
  end

  protected

  def search_attrs
    attrs = {}

    params[:player].try(:each) do |param, value|
      # next if %w(date_from date_to).include?(param)
      attrs[param] = value if value.present? && value != [""]
    end

    attrs
  end

  def search_scope(scope)
    query_attrs.each do |it|
      scope = it.is_a?(Array) ? scope.where(*it) : scope.where(it)
    end

    scope
  end

  def query_attrs
    result = [ search_attrs.reject { |name, value| %w(created_at name email phone_no_mask).include?(name) } ]

    if c_a = search_attrs['created_at']
      from = Date.parse(c_a).to_time
      to   = from + 24.hours

      result[0][:created_at] = (from .. to)
    end

    %w(name email).each do |attr|
      if value = search_attrs[attr]
        result << ["#{attr} like ? ", "%#{value}%"]
      end
    end

    if value = search_attrs['phone_no_mask']
      result << ["phone like ? ", "%#{value}%"]
    end


    result
  end


  def choose_layout
    params[:popup] == '1' ? 'blank' : 'application'
  end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_choose_button.slim
button.btn-block.btn-primary.choose-player data-player-id=player.id data-player-name=player.name Выбрать

app/views/players/_control_icons.slim
a href=edit_player_path(player)
  .i.fa.fa-pencil.fa-hover
/ br
/ = link_to player_path(player, authenticity_token: form_authenticity_token), method: :delete, data: {confirm: "Вы уверены?"} do
/   .i.fa.fa-trash.fa-hover

app/views/players/_date_input.slim
- input_attributes ||= {}
- input_type ||= :text_field

.form-group
  = form.label attribute, style: "color: black;"
  .input-group
    .input-group-addon
      i.fa.fa-calendar
    /= form.text_field attribute, {class: "form-control", 'data-inputmask': "'alias': 'dd/mm/yyyy'", "data-mask": true}.merge(input_attributes)

    = form.text_field attribute, {class: "form-control", 'data-inputmask': "'alias': 'dd/mm/yyyy'", "data-mask": true}.merge(input_attributes)



  = error_on record, attribute

app/views/players/_form.slim
a name='player-form'
- if !params[:popup] && !request.xhr?
  = form_for(player) do |form|
    = render 'form_body', form: form, player: player
- else
  = form_with(model: player, html: {id: 'new-player-form'}) do |form|
    = render 'form_body', form: form, player: player

app/views/players/_form_body.slim
.box-body
  = render "shared/form_group", form: form, record: player, attribute: :name, input_attributes: {autofocus: true}

  = render "shared/form_group", form: form, record: player, attribute: :city, input_type: :select, select_options: ['Сургут']

  = render "players/phone_input", player: player, form: form, attribute: :phone
  = render "players/phone_input", player: player, form: form, attribute: :phone2
  = render "shared/form_group", form: form, record: player, attribute: :email, input_attributes: {autocomplete: "email"}


  = render "shared/check_box", form: form, record: player, attribute: :blacklist
  = render "shared/check_box", form: form, record: player, attribute: :receive_email
  = render "shared/check_box", form: form, record: player, attribute: :receive_sms


  = render "shared/form_group", form: form, record: player, attribute: :city, input_type: :select, select_options: ['Сургут']

  = render "shared/form_group", form: form, record: player, attribute: :male, input_type: :select, select_options: [['Мужской', 1], ['Женский', 0]]

  = render "shared/form_group", form: form, record: player, attribute: :info_source, input_type: :select, select_options: ['Друзья', 'Интернет', 'Соц. сети', 'Другое']


  = render "shared/form_group", form: form, record: player, attribute: :comment


.box-header.with-border
  h3.box-title Информация о ребенке

.box-body
  = render "shared/form_group", form: form, record: player, attribute: :child_name, input_attributes: {autofocus: true}

  /= render "players/date_input", record: player, form: form, attribute: :child_birth_date, input_attributes: {id: 'datepicker'}
  = render "players/date_input", record: player, form: form, attribute: :child_birth_date

.box-footer
  = form.submit(player.new_record? ? "Создать" : "Сохранить")
  / = form.submit(player.new_record? ? "Создать" : "Сохранить")

app/views/players/_phone_input.slim
- record ||= form.object

.form-group class=error_class(record, attribute)
  = form.label attribute, style: "color: black;"

  .input-group
    .input-group-addon
      i.fa.fa-phone

    = form.text_field attribute, class: "form-control", 'data-inputmask': '"mask": "+7 (999) 999-9999"', 'data-mask': true

  = error_on record, attribute

app/views/players/_search.slim
- @model = :player

= form_for @player, url: players_path, method: :get do |form|
  .box-body
    .row
      .col-md-4
        = render "shared/simple_select_input", form: form, attribute: :city, select_options: ['Сургут'], no_blank: true

      .col-md-4
        = render "shared/form_group", form: form, attribute: :name

      .col-md-4
        = render "shared/form_group", form: form, attribute: :email

    .row
      .col-md-4
        = render "phone_input", form: form, attribute: :phone

      .col-md-4
        = render "shared/form_group", form: form, attribute: :phone_no_mask

      .col-md-4
        = render "shared/simple_date_input", form: form, attribute: :created_at
        = hidden_field_tag :popup, params[:popup]
    /
    / .row
    /   .col-md-4
    /     = render "shared/collection_select", form: form, attribute: :manager_id, collection: User.all
    /
    /   .col-md-4
    /     = render "shared/collection_select", form: form, attribute: :player_id, collection: Player.all
    /
    /   .col-md-4
    /     = render "shared/simple_date_input", form: form, attribute: :created_at, label: "Создано"
    /
    / .row
    /   .col-md-4
    /     = render "shared/simple_select_input", form: form, attribute: :game_center, select_options: CorpPack::ATTR_VALUES[:game_center], no_blank: true
    /
    /   .col-md-4
    /     = render "shared/simple_date_input", form: form, attribute: :prepayed_at
    /

  .box-footer
    .row
      .col-md-12
        / div style='float:right'
        = form.submit("Найти")

app/views/players/_table.html.slim
- columns = [:name, :phone, :email, :city, :created_at, nil]
- last_column = params[:popup] == '1' ? '_choose_button' : '_control_icons'

= render 'shared/sortable_table', collection: @players, \
    columns: columns, \
    values: { nil => last_column }

app/views/players/index.slim
h2.page-header Игроки

.row
  .col-md-12
    .box.box-primary
      .box-header.with-border
        h3.box-title Параметры поиска
      = render 'search'

      .box-header.with-border
        h3.box-title Игроки

      .box-body
        a name='search-results'
        = render 'table'
      - unless params[:popup]
        .box-footer
          = link_to "Создать", new_player_url

app/views/players/new.slim
.row
  .col-md-12
    .box.box-primary
      .box-header.with-border
        h3.box-title Новый игрок
      = render "form", player: @player





- content_for(:styles) do
  |
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="/admin_lte/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/admin_lte/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/admin_lte/bower_components/Ionicons/css/ionicons.min.css">
    <!-- daterange picker -->
    <link rel="stylesheet" href="/admin_lte/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="/admin_lte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="/admin_lte/plugins/iCheck/all.css">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="/admin_lte/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css">
    <!-- Bootstrap time Picker -->
    <link rel="stylesheet" href="/admin_lte/plugins/timepicker/bootstrap-timepicker.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="/admin_lte/bower_components/select2/dist/css/select2.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/admin_lte/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/admin_lte/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

- content_for :scripts do
  |
    <!-- jQuery 3 -->
    <script src="/admin_lte/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="/admin_lte/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Select2 -->
    <script src="/admin_lte/bower_components/select2/dist/js/select2.full.min.js"></script>
    <!-- InputMask -->
    <script src="/admin_lte/plugins/input-mask/jquery.inputmask.js"></script>
    <script src="/admin_lte/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
    <script src="/admin_lte/plugins/input-mask/jquery.inputmask.extensions.js"></script>
    <!-- date-range-picker -->
    <script src="/admin_lte/bower_components/moment/min/moment.min.js"></script>
    <script src="/admin_lte/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- bootstrap datepicker -->
    <script src="/admin_lte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!-- bootstrap color picker -->
    <script src="/admin_lte/bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
    <!-- bootstrap time picker -->
    <script src="/admin_lte/plugins/timepicker/bootstrap-timepicker.min.js"></script>
    <!-- SlimScroll -->
    <script src="/admin_lte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- iCheck 1.0.1 -->
    <script src="/admin_lte/plugins/iCheck/icheck.min.js"></script>
    <!-- FastClick -->
    <script src="/admin_lte/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="/admin_lte/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/admin_lte/dist/js/demo.js"></script>
    <!-- Page script -->

    <script src="/javascripts/datepicker-ru.js"></script>

    <script>
      $(function () {
        //Initialize Select2 Elements
        $('.select2').select2()

        //Datemask dd/mm/yyyy
        $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
        //Datemask2 mm/dd/yyyy
        $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
        //Money Euro
        $('[data-mask]').inputmask()

        //Date range picker
        $('#reservation').daterangepicker()
        //Date range picker with time picker
        $('#reservationtime').daterangepicker({ timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A' })
        //Date range as a button
        $('#daterange-btn').daterangepicker(
          {
            ranges   : {
              'Today'       : [moment(), moment()],
              'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
              'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
              'Last 30 Days': [moment().subtract(29, 'days'), moment()],
              'This Month'  : [moment().startOf('month'), moment().endOf('month')],
              'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            startDate: moment().subtract(29, 'days'),
            endDate  : moment()
          },
          function (start, end) {
            $('#daterange-btn span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
          }
        )

        //Date picker
        $('#datepicker').datepicker({
          closeText: "Закрыть",
          prevText: "&#x3C;Пред",
          nextText: "След&#x3E;",
          currentText: "Сегодня",
          monthNames: [ "Январь","Февраль","Март","Апрель","Май","Июнь",
          "Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь" ],
          monthNamesShort: [ "Янв","Фев","Мар","Апр","Май","Июн",
          "Июл","Авг","Сен","Окт","Ноя","Дек" ],
          dayNames: [ "воскресенье","понедельник","вторник","среда","четверг","пятница","суббота" ],
          dayNamesShort: [ "вск","пнд","втр","срд","чтв","птн","сбт" ],
          dayNamesMin: [ "Вс","Пн","Вт","Ср","Чт","Пт","Сб" ],
          weekHeader: "Нед",
          dateFormat: "dd.mm.yy",
          firstDay: 1,
          isRTL: false,
          showMonthAfterYear: false,
          yearSuffix: "" ,
          autoclose: true})

        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass   : 'iradio_minimal-blue'
        })
        //Red color scheme for iCheck
        $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
          checkboxClass: 'icheckbox_minimal-red',
          radioClass   : 'iradio_minimal-red'
        })
        //Flat red color scheme for iCheck
        $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
          checkboxClass: 'icheckbox_flat-green',
          radioClass   : 'iradio_flat-green'
        })

        //Colorpicker
        $('.my-colorpicker1').colorpicker()
        //color picker with addon
        $('.my-colorpicker2').colorpicker()

        //Timepicker
        $('.timepicker').timepicker({
          showInputs: false
        })
      })
    </script>